### ISSUE TITLE
How to import the settings

### ISSUE THREAD

**Issue by Flaburgan** [yuc8939/vs-eclipse#1]
Hello, thank you for providing this! I'm also new to VS and don't want to re-learn all the key shortcuts I'm used to with Eclipse. But how can I actually import your file? In the Tools menu I found an "Import / export settings" actions which allows me to indeed import your file, but then even after restarting Visual Studio the new shortcuts are not working...

**Comment by yuc8939** [comment]
Hi Flaburgan,
Are you using Visual Studio 2019? 
Use Tools -> Import / export settings -> Import selected environment settings -> No, just import new settings... -> Browse and choose my .vssettings file -> Finish
The new settings should apply without a restart.

**Comment by Flaburgan** [comment]
I may have been confused because the shortcut I was looking for was mostly Ctrl Shift G and this one isn't working. Looks like the other ones are okay. Closing.

**Comment by yuc8939** [comment]
Okay.. Did you use Ctrl Shift G for "Find Usages In File" ? I rarely use that, and I prefer Ctrl-G (Find Usages) and that works in my setting.
